pipeline:

  test:
    image: quay.io/ukhomeofficedigital/openjdk8:v1.8.0.171
    commands:
      - ./gradlew test | grep -v 'Download http'
    when:
      branches: [ master ]
      event: push

services:

  selenium:
    image: selenium/standalone-chrome

  ui:
    image: quay.io/ukhomeofficedigital/pttg-ip-fm-ui:build-95
    environment:
      - API_ROOT=http://api:8081
      - FEEDBACK_ROOT=http://feedback:8080

  api:
    image: quay.io/ukhomeofficedigital/pttg-ip-api:build-127
    environment:
      - HMRC_SERVICE_URL=http://hmrc:8100
      - PTTG_AUDIT_URL=http://audit:8083

  audit:
    image: quay.io/ukhomeofficedigital/pttg-ip-audit:build-73

  hmrc:
    image: quay.io/ukhomeofficedigital/pttg-ip-hmrc:build-157
    environment:
      - BASE_HMRC_ACCESS_CODE_URL=http://hmrc-access:8090
      - PTTG_AUDIT_URL=http://audit:8083
      - BASE_HMRC_URL=http://test:8111

  hmrc-access:
    image: quay.io/ukhomeofficedigital/pttg-ip-hmrc-access-code:build-54
    environment:
      - PTTG_AUDIT_URL=http://audit:8083
      - BASE_HMRC_URL=http://test:8111

  feedback:
    image: quay.io/ukhomeofficedigital/pttg-feedback:build-41



