pipeline:

  test:
    image: quay.io/ukhomeofficedigital/openjdk8:v1.8.0.171
    commands:
      - ./gradlew test --stacktrace -i
    when:
      branches: [ master, EE-4476/e2e-tests ]
      event: push

services:
  ui:
    image: "quay.io/ukhomeofficedigital/pttg-ip-fm-ui:build-95"
    ports: "8000:8000"
