pipeline:

  test:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/pttg-ip-e2e-tests.git
      - cd pttg-ip-e2e-tests
      - ./gradlew test
    when:
      branch: master, e2e-tests
      event: push

services:
  ui:
    image: "quay.io/ukhomeofficedigital/pttg-ip-fm-ui:build-95"
    ports: "8000:8000"
